/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kzcse_jni_NativeCalculator */

#ifndef _Included_kzcse_jni_NativeCalculator
#define _Included_kzcse_jni_NativeCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kzcse_jni_NativeCalculator
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_kzcse_jni_NativeCalculator_add
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
