/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kzcse_jni_NativeCode */

#ifndef _Included_kzcse_jni_NativeCode
#define _Included_kzcse_jni_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kzcse_jni_NativeCode
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kzcse_jni_NativeCode_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
