/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kzcse_jni_register_RegisterNativeBasic */

#ifndef _Included_kzcse_jni_register_RegisterNativeBasic
#define _Included_kzcse_jni_register_RegisterNativeBasic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kzcse_jni_register_RegisterNativeBasic
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kzcse_jni_register_RegisterNativeBasic_hello
  (JNIEnv *, jclass);
// Called to register native methods dynamically
JNIEXPORT void JNICALL Java_kzcse_jni_register_NativeUtils_registerNative(JNIEnv* env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
